# Generated by Django 3.1.4 on 2021-03-01 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0002_문진결과_questionnaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='질문지',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='질문지',
            name='ownership',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='corona.대대'),
        ),
    ]
