# Generated by Django 3.1.4 on 2021-03-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0003_auto_20210301_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='문진결과',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='질문지',
            name='last_revised',
            field=models.DateField(),
        ),
    ]
