# Generated by Django 3.1.4 on 2021-03-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0004_auto_20210301_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='질문지',
            name='last_revised',
            field=models.DateField(auto_now_add=True),
        ),
    ]
