# Generated by Django 3.1.4 on 2021-03-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0005_auto_20210301_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='문진결과',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
