# Generated by Django 3.1.4 on 2021-03-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0006_auto_20210307_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='문진결과',
            name='date',
            field=models.DateField(),
        ),
    ]
