from django.core.management.base import BaseCommand, CommandError
from corona.models import 관리자, 간부, 대대, 여단, 사단, 제출여부, 문진결과, 질문지
from datetime import date, timedelta

class Command(BaseCommand):
    help = 'Creates Demo Data for the data'
    
    # create demo
    def handle(self, *args, **options):
        if len(사단.objects.all()) == 0:
            division = 사단(name = "제8기동사단")
            division.save()
        else: division = 사단.objects.get(id = 1)
        if len(여단.objects.all()) == 0:
            brigade1 = 여단(name = "직할대", division = division)
            brigade1.save()
            brigade2 = 여단(name = "참모처", division = division)
            brigade2.save()
        else: 
            brigade1 = 여단.objects.get(id = 1)
            brigade2 = 여단.objects.get(id = 2)
        if len(대대.objects.all()) == 0:
            battalion1 = 대대(name = "정보통신", brigade = brigade1)
            battalion1.save()
            battalion2 = 대대(name = "의무", brigade = brigade1)
            battalion2.save()
            battalion3 = 대대(name = "공병", brigade = brigade1)
            battalion3.save()
            battalion4 = 대대(name = "지통처", brigade = brigade2)
            battalion4.save()
        else: 
            battalion1 = 대대.objects.get(id = 1)
            battalion2 = 대대.objects.get(id = 2)
            battalion3 = 대대.objects.get(id = 3)
            battalion4 = 대대.objects.get(id = 4)
        if len(관리자.objects.all()) == 0:
            admin1 = 관리자(username = "함희성", password = "A", access_level = "Di", adminofdiv = division)
            admin1.save()
            admin2 = 관리자(username = "직할참모", password = "A", access_level = "Br", adminofbrig = brigade1)
            admin2.save()
            admin3 = 관리자(username = "참모처", password = "A", access_level = "Br", adminofbrig = brigade2)
            admin3.save()
            admin4 = 관리자(username = "홍성인", password = "A", access_level = "Ba", adminofbatta = battalion1)
            admin4.save()
            admin5 = 관리자(username = "의무머", password = "A", access_level = "Ba", adminofbatta = battalion2)
            admin5.save()
            admin6 = 관리자(username = "공병머", password = "A", access_level = "Ba", adminofbatta = battalion3)
            admin6.save()
            admin7 = 관리자(username = "지통참머", password = "A", access_level = "Ba", adminofbatta = battalion4)
            admin7.save()
        else:
            admin1 = 관리자.objects.get(id = 1)
            admin2 = 관리자.objects.get(id = 2)
            admin3 = 관리자.objects.get(id = 3)
            admin4 = 관리자.objects.get(id = 4)
            admin5 = 관리자.objects.get(id = 5)
            admin6 = 관리자.objects.get(id = 6)
            admin7 = 관리자.objects.get(id = 7)
        if len(간부.objects.all()) == 0:
            officer1 = 간부(username = "강신희", password = "A",battalion = battalion1)
            officer1.save()    
            officer2 = 간부(username = "조예나", password = "A",battalion = battalion1)
            officer2.save()
            officer3 = 간부(username = "장현", password = "A",battalion = battalion1)
            officer3.save()
            officer4 = 간부(username = "공병진", password = "A",battalion = battalion1)
            officer4.save()
            officer5 = 간부(username = "정인준", password = "A",battalion = battalion1)
            officer5.save()
            officer6 = 간부(username = "의무", password = "A",battalion = battalion2)
            officer6.save()
            officer7 = 간부(username = "공병", password = "A",battalion = battalion3)
            officer7.save()
            officer8 = 간부(username = "지통처", password = "A",battalion = battalion4)
            officer8.save()
        else:
            officer1 = 간부.objects.get(id = 1)
            officer2 = 간부.objects.get(id = 2)
            officer3 = 간부.objects.get(id = 3)
            officer4 = 간부.objects.get(id = 4)
            officer5 = 간부.objects.get(id = 5)
            officer6 = 간부.objects.get(id = 6)
            officer7 = 간부.objects.get(id = 7)
            officer8 = 간부.objects.get(id = 8)
        if len(질문지.objects.all()) == 0:
            questionnaire1 = 질문지(ownership = battalion1, Q1 = "1", Q2 = "2",Q3 = "3",Q4 = "4",Q5 = "5", Q6 = "6",Q7 = "7",Q8 = "8",Q9 = "9",Q10 = "10")
            questionnaire1.save()
            questionnaire2 = 질문지(ownership = battalion2, Q1 = "1", Q2 = "2",Q3 = "3",Q4 = "4",Q5 = "5", Q6 = "6",Q7 = "7",Q8 = "8",Q9 = "9",Q10 = "10")
            questionnaire2.save()
            questionnaire3 = 질문지(ownership = battalion3, Q1 = "1", Q2 = "2",Q3 = "3",Q4 = "4",Q5 = "5", Q6 = "6",Q7 = "7",Q8 = "8",Q9 = "9",Q10 = "10")
            questionnaire3.save()
            questionnaire4 = 질문지(ownership = battalion4, Q1 = "1", Q2 = "2",Q3 = "3",Q4 = "4",Q5 = "5", Q6 = "6",Q7 = "7",Q8 = "8",Q9 = "9",Q10 = "10")
            questionnaire4.save()
        else:
            questionnaire1 = 질문지.objects.get(ownership = battalion1)
            questionnaire2 = 질문지.objects.get(ownership = battalion2)
            questionnaire3 = 질문지.objects.get(ownership = battalion3)
            questionnaire4 = 질문지.objects.get(ownership = battalion4)
        if len(문진결과.objects.filter(date = date.today())) == 0:
            result1 = 문진결과(owner = officer1, battalion = battalion1, questionnaire = questionnaire1, A1 = False, A2 = True, A3 = False, A4 = False, A5 = False, A6 = False, A7 = False, A8 = False, A9 = False, A10 = False, is_fine = False)
            result1.save()
            result2 = 문진결과(owner = officer2, battalion = battalion1, questionnaire = questionnaire1, A1 = False, A2 = False, A3 = False, A4 = False, A5 = False, A6 = False, A7 = False, A8 = False, A9 = False, A10 = False, is_fine = True)
            result2.save()
            result3 = 문진결과(owner = officer3, battalion = battalion1, questionnaire = questionnaire1, A1 = False, A2 = False, A3 = False, A4 = False, A5 = False, A6 = False, A7 = False, A8 = False, A9 = False, A10 = False, is_fine = True)
            result3.save()
            result4 = 문진결과(owner = officer4, battalion = battalion1, questionnaire = questionnaire1, A1 = False, A2 = False, A3 = False, A4 = False, A5 = False, A6 = False, A7 = False, A8 = False, A9 = False, A10 = False, is_fine = True)
            result4.save()
            result5 = 문진결과(owner = officer5, battalion = battalion1, questionnaire = questionnaire1, A1 = False, A2 = False, A3 = False, A4 = False, A5 = False, A6 = False, A7 = False, A8 = False, A9 = False, A10 = False, is_fine = True)
            result5.save()
            result6 = 문진결과(owner = officer6, battalion = battalion2, questionnaire = questionnaire2, A1 = False, A2 = False, A3 = False, A4 = False, A5 = False, A6 = False, A7 = False, A8 = False, A9 = False, A10 = False, is_fine = True)
            result6.save()
            result7 = 문진결과(owner = officer7, battalion = battalion3, questionnaire = questionnaire3, A1 = False, A2 = False, A3 = False, A4 = False, A5 = False, A6 = False, A7 = False, A8 = False, A9 = False, A10 = False, is_fine = True)
            result7.save()
        if len(제출여부.objects.filter(date = date.today())) == 0:
            submission1 = 제출여부(brigade = brigade1)
            submission1.save()
            submission2 = 제출여부(battalion = battalion1)
            submission2.save()
            submission3 = 제출여부(battalion = battalion2)
            submission3.save()
            submission4 = 제출여부(battalion = battalion3)
            submission4.save()
            submission5 = 제출여부(battalion = battalion4)
            submission5.save()

        self.stdout.write(self.style.SUCCESS('Sucessfully added demo_data'))